# Generated by Django 2.0.5 on 2018-05-06 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='posting_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время постинга'),
        ),
    ]
