# Generated by Django 2.0.5 on 2018-05-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20180513_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_post_time_utc',
            field=models.DateTimeField(null=True),
        ),
    ]
