# Generated by Django 2.0.5 on 2018-05-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_group_is_posting_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceToken',
            fields=[
                ('app_service_token', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Сервисный ключ приложения')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='app_service_token',
        ),
    ]
