# Generated by Django 2.0.5 on 2018-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_group_is_posting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='ФИО'),
        ),
    ]
