# Generated by Django 2.0.5 on 2018-05-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20180524_0607'),
        ('posting', '0008_user_domain_or_id'),
    ]

    operations = [
    ]
