# Generated by Django 2.0.5 on 2018-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0013_group_is_pin_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_white_list', models.TextField(blank=True, max_length=1024, null=True, verbose_name='White list domain/id людей или сообществ (через пробел)')),
                ('words_stop_list', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Ключевые слова для удаления (через пробел)')),
            ],
            options={
                'verbose_name': 'Правило модерации',
                'verbose_name_plural': 'Правила модерации',
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AlterModelOptions(
            name='servicetoken',
            options={'verbose_name': 'Сервисный токен', 'verbose_name_plural': 'Сервисные токены'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
    ]
