# Generated by Django 2.0.5 on 2018-06-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0014_auto_20180612_1659'),
        ('posting', '0014_adrecord'),
    ]

    operations = [
    ]
