# Generated by Django 2.0.5 on 2018-06-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0016_group_is_horoscopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='RGB_image_tone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Применить RBG тон к картинке\nВ формате 255,0,0'),
        ),
    ]
