# Generated by Django 2.0.5 on 2018-06-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0018_auto_20180628_0932'),
        ('posting', '0018_auto_20180628_1942'),
    ]

    operations = [
    ]
