# Generated by Django 2.0.5 on 2018-07-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0020_auto_20180701_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='members_growth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='number_of_ad_posts_yesterday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='number_of_posts_yesterday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='statistic_url',
            field=models.URLField(blank=True, default='', max_length=256, verbose_name='Ссылка на статистику'),
        ),
        migrations.AddField(
            model_name='group',
            name='statistics_last_update_date',
            field=models.DateTimeField(null=True),
        ),
    ]
