# Generated by Django 2.0.5 on 2018-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0021_auto_20180707_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members_count',
            field=models.IntegerField(null=True, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members_growth',
            field=models.IntegerField(null=True, verbose_name='Прирост'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number_of_ad_posts_yesterday',
            field=models.IntegerField(null=True, verbose_name='Реклама за вчера'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number_of_posts_yesterday',
            field=models.IntegerField(null=True, verbose_name='Посты за вчера'),
        ),
    ]
