# Generated by Django 2.0.5 on 2018-07-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0022_auto_20180707_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_changing_image_to_square_enabled',
            field=models.BooleanField(default=False, verbose_name='Приводить изображения к более квадратному виду?'),
        ),
    ]
