# Generated by Django 2.0.5 on 2018-07-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0024_auto_20180712_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_merge_images_enabled',
            field=models.BooleanField(default=False, verbose_name='Объединять 6 изображений в одно?'),
        ),
    ]
