# Generated by Django 2.0.5 on 2018-09-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0027_group_is_text_delete_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_replace_russian_with_english',
            field=models.BooleanField(default=False, verbose_name='Заменять русские буквы английскими?'),
        ),
    ]
