# Generated by Django 2.0.5 on 2018-09-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0032_group_preferred_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='preferred_audience',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Женщины'), (2, 'Мужчины')], default=0, verbose_name='Предпочтительная аудитория'),
        ),
    ]
