# Generated by Django 2.0.5 on 2018-09-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0034_merge_20180906_1711'),
        ('posting', '0035_group_sex_last_update_date'),
    ]

    operations = [
    ]
