# Generated by Django 2.0.5 on 2018-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0038_group_is_delete_audio_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_additional_text_enabled',
            field=models.BooleanField(default=False, verbose_name='Добавлять к записи дополнительный текст?'),
        ),
    ]
