# Generated by Django 2.0.5 on 2018-09-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0039_group_is_additional_text_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaltext',
            name='text_plural',
            field=models.TextField(default='', max_length=1024, verbose_name='Дополнительный текст, множественное число'),
        ),
        migrations.AlterField(
            model_name='additionaltext',
            name='text',
            field=models.TextField(default='', max_length=1024, verbose_name='Дополнительный текст, единственное число'),
        ),
    ]
