# Generated by Django 2.0.5 on 2018-10-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0040_auto_20180929_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_movies',
            field=models.BooleanField(default=False, verbose_name='Постинг из источника фильмов задействован?'),
        ),
    ]
