# Generated by Django 2.0.5 on 2019-03-28 18:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0044_auto_20190125_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banned_origin_attachment_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('audio', 'audio'), ('video', 'video'), ('gif', 'gif'), ('picture', 'picture')], max_length=16, null=True), blank=True, help_text="Типы вложений записей, которые не нужны в этой группе. Примеры:['audio', 'video', 'gif', 'picture']", null=True, size=None, verbose_name='Недопустимые вложения для записей'),
        ),
    ]
