# Generated by Django 2.0.5 on 2019-03-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0045_group_banned_origin_attachment_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_delete_audio_enabled',
        ),
    ]
