# Generated by Django 2.0.5 on 2019-05-14 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0041_scrapinghistory'),
        ('posting', '0047_servicetoken_last_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidates_number', models.IntegerField()),
                ('candidates_internal_ids', models.CharField(max_length=2500)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='posting.Group')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='scraping.Record')),
            ],
            options={
                'verbose_name': 'История постинга',
                'verbose_name_plural': 'История постинга',
            },
        ),
    ]
