# Generated by Django 2.0.5 on 2020-03-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0049_group_is_copyright_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('common', 'Обычная'), ('movie common', 'Обычные фильмы'), ('movie special', 'Сторонние фильмы'), ('music common', 'Обычная музыка'), ('horoscopes common', 'Обычные гороскопы')], default='common', max_length=128, verbose_name='Тип группы'),
        ),
    ]
