# Generated by Django 2.0.5 on 2020-07-29 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0051_auto_20200331_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='posting_interval',
            field=models.IntegerField(default=60, help_text='С этой минуты будет начинаться отчёт постинга.', validators=[django.core.validators.MaxValueValidator(1440), django.core.validators.MinValueValidator(30)], verbose_name='Минута отчета'),
        ),
        migrations.AddField(
            model_name='group',
            name='posting_minute_base',
            field=models.IntegerField(default=0, help_text='С этой минуты будет начинаться отчёт постинга.', validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)], verbose_name='Минута отчета'),
        ),
    ]
