# Generated by Django 2.0.5 on 2020-09-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0055_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='posting.Group'),
        ),
    ]
