# Generated by Django 2.0.5 on 2020-09-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0057_auto_20200926_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='reason',
            field=models.CharField(choices=[('ad', 'ad'), ('lack of records', 'lack of records'), ('rate limit', 'rate limit'), ('recent posts', 'recent posts'), ('posting', 'posting')], max_length=64, null=True),
        ),
    ]
