# Generated by Django 2.2 on 2021-12-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0058_auto_20200926_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='donors_alternation',
            field=models.BooleanField(default=True, help_text='Если настройка включена, 2 поста из одного донора подряд не будут выходить', verbose_name='Чередование доноров'),
        ),
    ]
