# Generated by Django 3.2.23 on 2024-02-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0063_user_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Пользовательский Access token'),
        ),
    ]
