# Generated by Django 3.2.23 on 2024-05-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0064_alter_user_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='horoscope_postfix',
            field=models.CharField(blank=True, default='', help_text='Работает, если включена настройка ', max_length=256, verbose_name='Текст после обрезки основного текста гороскопа'),
        ),
    ]
