from .delete_old_ads import *
from .delete_old_stat import *
from .examine_groups import *
from .pin_best_post import *
from .post_horoscope import *
from .post_movie import *
from .post_music import *
from .post_record import *
from .sex_statistics_weekly import *
from .update_statistics import *
