# Generated by Django 2.0.5 on 2018-05-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Domain/id группы донора')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity_of_line_breaks', models.IntegerField(blank=True, null=True)),
                ('min_quantity_of_videos', models.IntegerField(blank=True, null=True)),
                ('min_quantity_of_images', models.IntegerField(blank=True, null=True)),
                ('min_quantity_of_gifs', models.IntegerField(blank=True, null=True)),
                ('min_text_length', models.IntegerField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scraping.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2048, null=True)),
                ('rate', models.IntegerField(null=True)),
                ('post_in_donor_date', models.DateTimeField(null=True)),
                ('add_to_db_date', models.DateTimeField(null=True)),
                ('post_in_group_date', models.DateTimeField(null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scraping.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('video_id', models.IntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Record')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Record'),
        ),
    ]
