# Generated by Django 2.0.5 on 2018-05-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_involved',
            field=models.BooleanField(default=True, verbose_name='Донор задействован?'),
        ),
        migrations.AddField(
            model_name='record',
            name='likes_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='record_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='reposts_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='views_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.IntegerField(null=True),
        ),
    ]
