# Generated by Django 2.0.5 on 2018-05-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20180512_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filters', to='scraping.Donor'),
        ),
        migrations.AlterField(
            model_name='image',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraping.Record'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='record',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='scraping.Donor'),
        ),
        migrations.AlterField(
            model_name='video',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='scraping.Record'),
        ),
    ]
