# Generated by Django 2.0.5 on 2018-05-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20180513_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='add_to_db_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='post_in_donor_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='post_in_group_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
