# Generated by Django 2.0.5 on 2018-05-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_gif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(null=True)),
                ('audio_id', models.IntegerField(null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='scraping.Record')),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='min_quantity_of_audios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное количество аудиозаписей'),
        ),
    ]
