# Generated by Django 2.0.5 on 2018-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0017_horoscope_post_in_donor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='min_quantity_of_films',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное количество фильмов (видео длинной от 20 минут)'),
        ),
    ]
