# Generated by Django 2.0.5 on 2018-07-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0018_filter_min_quantity_of_films'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_involved_now',
            field=models.BooleanField(default=False),
        ),
    ]
