# Generated by Django 2.0.5 on 2018-08-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0019_record_is_involved_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='record',
            name='donor_url',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='record',
            name='group_url',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='record',
            name='post_in_group_id',
            field=models.IntegerField(null=True),
        ),
    ]
