# Generated by Django 2.0.5 on 2018-09-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0022_auto_20180902_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='females_count',
            field=models.IntegerField(default=0, verbose_name='Лайков от женщин'),
        ),
        migrations.AddField(
            model_name='record',
            name='males_count',
            field=models.IntegerField(default=0, verbose_name='Лайков от мужчин'),
        ),
        migrations.AddField(
            model_name='record',
            name='males_females_ratio',
            field=models.FloatField(default=1.0, verbose_name='Соотношение мужчин к женщинам в лайках'),
        ),
        migrations.AddField(
            model_name='record',
            name='unknown_count',
            field=models.IntegerField(default=0, verbose_name='Лайков от неопределенного пола'),
        ),
    ]
