# Generated by Django 2.0.5 on 2018-10-16 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0023_auto_20180905_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('rating', models.FloatField(null=True)),
                ('release_year', models.IntegerField(null=True)),
                ('runtime', models.CharField(max_length=16, null=True, verbose_name='ЧЧ:ММ')),
                ('overview', models.CharField(max_length=512, null=True)),
                ('poster', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=8)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='scraping.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'pending'), (3, 'downloaded'), (4, 'uploaded'), (5, 'posted'), (6, 'failed')], default=1, verbose_name='Статус')),
                ('url', models.CharField(max_length=128)),
                ('file_path', models.CharField(max_length=128)),
                ('post_in_group_date', models.DateTimeField(null=True, verbose_name='Дата постинга в сообществе')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='scraping.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='scraping.Movie'),
        ),
        migrations.AddField(
            model_name='frame',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='scraping.Movie'),
        ),
    ]
