# Generated by Django 2.0.5 on 2018-10-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0025_auto_20181016_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='post_in_group_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='post_in_group_date',
            field=models.DateTimeField(null=True, verbose_name='Дата постинга в сообществе'),
        ),
    ]
