# Generated by Django 2.0.5 on 2018-11-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0041_group_is_movies'),
        ('scraping', '0029_auto_20181107_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='posting.Group'),
        ),
    ]
