# Generated by Django 2.0.5 on 2019-02-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0032_auto_20190103_0832'),
        ('scraping', '0031_trailer_vk_url'),
    ]

    operations = [
    ]
