# Generated by Django 2.0.5 on 2019-03-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0034_donor_is_banned'),
        ('scraping', '0034_attachment'),
    ]

    operations = [
    ]
