# Generated by Django 2.0.5 on 2019-03-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0035_merge_20190330_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='average_views_number',
            field=models.IntegerField(null=True, verbose_name='Среднее количество просмотров поста'),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'ready'), (3, 'posting'), (4, 'posted'), (5, 'failed')], default=1, verbose_name='Статус записи'),
        ),
    ]
