# Generated by Django 2.0.5 on 2019-04-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0038_merge_20190414_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horoscope',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='horoscope',
            name='post_in_donor_date',
        ),
    ]
