# Generated by Django 2.0.5 on 2019-05-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0039_auto_20190419_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='h_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scraping.Horoscope'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='origin_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scraping.Record'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='vk_attachment_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
