# Generated by Django 2.0.5 on 2019-06-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0041_scrapinghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='donor',
            name='ban_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'old'), (2, 'disabled')], null=True),
        ),
    ]
