# Generated by Django 2.0.5 on 2020-04-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0043_auto_20190831_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='candidate_number',
            field=models.IntegerField(null=True, verbose_name='Идекс по рейтингу'),
        ),
    ]
