# Generated by Django 2.0.5 on 2020-06-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0045_auto_20200411_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='copyright_text',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
