# Generated by Django 2.0.5 on 2020-08-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0047_image_index_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='index_number',
            field=models.IntegerField(default=0),
        ),
    ]
