# Generated by Django 2.2 on 2021-12-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0053_filter_max_text_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'ready'), (3, 'posting'), (4, 'posted'), (5, 'failed'), (6, 'filtered')], default=1, verbose_name='Статус записи'),
        ),
    ]
