# Generated by Django 2.0.5 on 2018-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('key_type', models.CharField(choices=[('bool', 'bool'), ('str', 'str'), ('int', 'int')], max_length=32)),
                ('value', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
