# Generated by Django 2.0.5 on 2018-05-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Domain/id группы цели')),
                ('donors', models.ManyToManyField(blank=True, to='scraping.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=64, verbose_name='Пароль')),
                ('app_service_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='Сервисный ключ приложения')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posting.User'),
        ),
    ]
