# Generated by Django 2.0.5 on 2018-05-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20180512_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='id',
            new_name='domain_or_id',
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='app_id',
            field=models.CharField(max_length=256, null=True, verbose_name='ID приложения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='donors',
            field=models.ManyToManyField(blank=True, to='scraping.Donor'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='posting.User'),
        ),
    ]
