# Generated by Django 2.0.5 on 2018-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20180517_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_posting_active',
            field=models.BooleanField(default=True, verbose_name='Постинг активен?'),
        ),
    ]
