# Generated by Django 2.0.5 on 2018-05-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20180524_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain_or_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Domain/id пользователя'),
        ),
    ]
