# Generated by Django 2.0.5 on 2018-05-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_group_callback_api_token'),
        ('posting', '0011_group_url'),
    ]

    operations = [
    ]
