# Generated by Django 2.0.5 on 2018-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0012_merge_20180525_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_pin_enabled',
            field=models.BooleanField(default=True, verbose_name='Закреплять лучшие посты?'),
        ),
    ]
