# Generated by Django 2.0.5 on 2018-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0017_group_rgb_image_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='RGB_image_tone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Применять RBG тон к изображениям'),
        ),
    ]
