# Generated by Django 2.0.5 on 2018-07-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0019_merge_20180628_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='RGB_image_tone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Применять RBG тон к изображениям (R G B factor)'),
        ),
    ]
