# Generated by Django 2.0.5 on 2018-07-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0023_group_is_changing_image_to_square_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_audios_shuffle_enabled',
            field=models.BooleanField(default=False, verbose_name='Перемешивать аудиозаписи?'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_photos_shuffle_enabled',
            field=models.BooleanField(default=False, verbose_name='Перемешивать фото?'),
        ),
    ]
