# Generated by Django 2.0.5 on 2018-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0025_group_is_merge_images_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_image_mirror_enabled',
            field=models.BooleanField(default=False, verbose_name='Отзеркаливать изображения без текста?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_text_filling_enabled',
            field=models.BooleanField(default=False, verbose_name='Переносить текст на изображение?'),
        ),
    ]
