# Generated by Django 2.0.5 on 2018-08-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0026_auto_20180721_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_text_delete_enabled',
            field=models.BooleanField(default=False, verbose_name='Убирать текст из постов?'),
        ),
    ]
