# Generated by Django 2.0.5 on 2018-08-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0028_additionaltext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaltext',
            options={'verbose_name': 'Дополнительные тексты'},
        ),
        migrations.AlterField(
            model_name='additionaltext',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='Дополнительный текст к записи'),
        ),
    ]
