# Generated by Django 2.0.5 on 2018-08-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0029_auto_20180825_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaltext',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Тексты'},
        ),
    ]
