# Generated by Django 2.0.5 on 2018-09-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0030_auto_20180825_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_used_additional_text_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
