# Generated by Django 2.0.5 on 2018-09-04 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0028_group_is_replace_russian_with_english'),
        ('posting', '0031_group_last_used_additional_text_id'),
    ]

    operations = [
    ]
