# Generated by Django 2.0.5 on 2018-09-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0031_group_last_used_additional_text_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='preferred_audience',
            field=models.IntegerField(default=0, verbose_name='Предпочтительная аудитория'),
        ),
    ]
