# Generated by Django 2.0.5 on 2018-09-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0032_merge_20180904_2312'),
        ('posting', '0033_auto_20180906_1706'),
    ]

    operations = [
    ]
