# Generated by Django 2.0.5 on 2018-09-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0036_merge_20180908_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='female_weekly_average_count',
            field=models.IntegerField(default=0, verbose_name='Среднее количество женщин за неделю'),
        ),
    ]
