# Generated by Django 2.0.5 on 2018-09-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0037_auto_20180909_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_delete_audio_enabled',
            field=models.BooleanField(default=False, verbose_name='Убирать аудио из постов?'),
        ),
    ]
