# Generated by Django 2.0.5 on 2019-01-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0043_auto_20190122_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenreEpithet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_for_male', models.TextField(default='', max_length=256, verbose_name='Эпитет для музыкального жанра мужского рода')),
                ('text_for_female', models.TextField(default='', max_length=256, verbose_name='Эпитет для музыкального жанра женского рода')),
            ],
            options={
                'verbose_name': 'Эпитет',
                'verbose_name_plural': 'Эпитеты',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='is_music_genre_epithet_enabled',
            field=models.BooleanField(default=False, verbose_name='Добавлять эпитет перед музыкальным жанром?'),
        ),
        migrations.AddField(
            model_name='group',
            name='last_used_music_genre_epithet_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='musicgenreepithet',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_genre_epithets', to='posting.Group'),
        ),
    ]
