# Generated by Django 2.0.5 on 2020-08-07 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0052_auto_20200729_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_horoscopes',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_movies',
        ),
        migrations.AlterField(
            model_name='group',
            name='posting_interval',
            field=models.IntegerField(default=60, help_text='Количество минут между постингом. Минимально - 30 минут. Максимально - 1410 (сутки).', validators=[django.core.validators.MaxValueValidator(1410), django.core.validators.MinValueValidator(30)], verbose_name='Интервал постинга'),
        ),
    ]
