# Generated by Django 2.0.5 on 2020-08-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0053_auto_20200802_1400'),
        ('posting', '0053_auto_20200807_1124'),
    ]

    operations = [
    ]
