# Generated by Django 2.0.5 on 2020-09-26 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0056_auto_20200914_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='active_before',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='posting.Group'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='reason',
            field=models.CharField(choices=[('ad', 'ad'), ('lack of records', 'lack of records'), ('rate limit', 'rate limit'), ('recent posts', 'recent posts')], max_length=64, null=True),
        ),
    ]
