# Generated by Django 2.2 on 2022-02-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0059_group_donors_alternation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor',
            field=models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация'),
        ),
    ]
