# Generated by Django 3.2.23 on 2024-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0062_auto_20220214_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Пользовательский токен'),
        ),
    ]
