# Generated by Django 3.2.23 on 2024-10-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0065_group_horoscope_postfix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='horoscope_postfix',
            field=models.TextField(blank=True, default='', help_text='Работает, если включена настройка ', max_length=256, verbose_name='Текст после обрезки основного текста гороскопа'),
        ),
    ]
