# Generated by Django 2.0.5 on 2018-05-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_auto_20180513_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationrule',
            name='id_white_list',
            field=models.TextField(max_length=1024, verbose_name='White list domain/id людей или сообществ (через пробел)'),
        ),
    ]
