# Generated by Django 2.0.5 on 2018-07-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0007_auto_20180707_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooktransaction',
            name='request_meta',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_processed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
