# Generated by Django 2.0.5 on 2018-07-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_auto_20180707_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default=None, max_length=4096, verbose_name='текст комментария'),
        ),
    ]
