# Generated by Django 2.2 on 2021-12-06 07:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0009_auto_20180707_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='webhooktransaction',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
