# Generated by Django 3.2.23 on 2024-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0010_auto_20211206_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=256)),
                ('code_verifier', models.CharField(max_length=128)),
                ('app_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=256)),
                ('access_token_lifetime', models.IntegerField()),
                ('refresh_token', models.CharField(max_length=256)),
                ('refresh_token_lifetime', models.IntegerField()),
                ('device_id', models.CharField(max_length=128)),
                ('app_id', models.CharField(max_length=256)),
            ],
        ),
    ]
