# Generated by Django 3.2.23 on 2024-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0011_authorizationtransactions_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token_lifetime',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='token',
            name='app_id',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='token',
            name='device_id',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token_lifetime',
            field=models.TextField(max_length=512),
        ),
    ]
