# Generated by Django 3.2.23 on 2024-10-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0023_userdatasubscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdatasubscribe',
            options={},
        ),
    ]
