# Generated by Django 3.2.23 on 2024-10-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0026_userdatasubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_community_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.TextField(max_length=512, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token_lifetime',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Access Token Lifetime'),
        ),
        migrations.AlterField(
            model_name='token',
            name='app_id',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='App ID'),
        ),
        migrations.AlterField(
            model_name='token',
            name='device_id',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Refresh Token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token_lifetime',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Refresh Token Lifetime'),
        ),
    ]
