# Generated by Django 2.0.5 on 2018-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_auto_20180516_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationrule',
            name='id_white_list',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='White list domain/id людей или сообществ (через пробел)'),
        ),
        migrations.AlterField(
            model_name='moderationrule',
            name='words_stop_list',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Ключевые слова для удаления (через пробел)'),
        ),
    ]
