# Generated by Django 2.0.5 on 2018-06-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_auto_20180519_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModerationRule',
        ),
    ]
