# Generated by Django 2.0.5 on 2018-07-07 15:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0005_delete_moderationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=64)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.IntegerField(null=True, verbose_name='идентификатор записи')),
                ('post_owner_id', models.IntegerField(null=True, verbose_name='идентификатор владельца записи')),
                ('comment_id', models.IntegerField(null=True, verbose_name='идентификатор комментария')),
                ('from_id', models.IntegerField(null=True, verbose_name='идентификатор автора комментария')),
                ('date', models.IntegerField(null=True, verbose_name='дата создания комментария в формате Unixtime')),
                ('text', models.CharField(default='', max_length=4096, verbose_name='текст комментария')),
                ('reply_to_user', models.IntegerField(null=True, verbose_name='идентификатор пользователя или сообщества, в ответ которому оставлен текущий комментарий')),
                ('reply_to_comment', models.IntegerField(null=True, verbose_name='идентификатор комментария, в ответ на который оставлен текущий')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField()),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('request_meta', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('status', models.CharField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error')], default=1, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='webhook_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moderation.WebhookTransaction'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attached_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='moderation.Comment'),
        ),
    ]
