# Generated by Django 2.0.5 on 2018-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_auto_20180707_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooktransaction',
            name='date_generated',
        ),
        migrations.AlterField(
            model_name='webhooktransaction',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
