# Generated by Django 3.2.23 on 2024-09-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0013_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
