# Generated by Django 3.2.23 on 2024-09-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0014_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text="Введите ключевые слова через ';'")),
                ('answers', models.FileField(default='file.txt', help_text='Загрузите файл .txt с ответами', upload_to='')),
                ('onlyword', models.BooleanField(default=False, help_text='Искать слова в предложении? (True/False)')),
            ],
        ),
    ]
