# Generated by Django 3.2.23 on 2024-09-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0015_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'permissions': [('moderation.view_filter', 'Can view filter'), ('moderation.edit_filter', 'Can edit filter')]},
        ),
    ]
