# Generated by Django 3.2.23 on 2024-09-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0016_alter_filter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'permissions': [('moderation.view_filter', 'Can view filter'), ('moderation.edit_filter', 'Can edit filter'), ('moderation.add_filter', 'Can add filter')]},
        ),
    ]
