# Generated by Django 3.2.23 on 2024-09-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0018_alter_filter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='answers',
            field=models.FileField(default='file.txt', help_text='Загрузите файл .txt с ответами.', upload_to=''),
        ),
    ]
