# Generated by Django 3.2.23 on 2024-10-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0021_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
