# Generated by Django 3.2.23 on 2024-10-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0022_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'User Data',
            },
        ),
    ]
