# Generated by Django 3.2.23 on 2024-10-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0024_alter_userdatasubscribe_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDataSubscribe',
        ),
    ]
