# Generated by Django 3.2.23 on 2024-10-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0025_delete_userdatasubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('group_id', models.TextField()),
                ('comment_id', models.TextField()),
                ('post_id', models.TextField()),
                ('owner_id', models.TextField()),
            ],
        ),
    ]
