# Generated by Django 3.2.23 on 2024-02-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_core', '0002_auto_20240204_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='tg_id',
            field=models.BigIntegerField(),
        ),
    ]
