# Generated by Django 3.2.23 on 2024-02-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_core', '0003_alter_channel_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgpost',
            name='tg_id',
            field=models.IntegerField(null=True),
        ),
    ]
