# Generated by Django 3.2.23 on 2024-03-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_core', '0005_internalhoroscopesourcelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
