# Generated by Django 3.2.23 on 2024-03-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_core', '0007_auto_20240317_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(editable=False)),
                ('modified_dt', models.DateTimeField(editable=False)),
                ('slug', models.CharField(max_length=128, unique=True, verbose_name='Уникальное имя шаблона.')),
                ('template', models.TextField(default='', verbose_name='Шаблон сообщения в html-формате.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
