# Generated by Django 2.0.5 on 2018-05-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20180517_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='post_in_group_date',
            field=models.DateTimeField(null=True),
        ),
    ]
