# Generated by Django 2.0.5 on 2018-05-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_auto_20180524_0652'),
        ('scraping', '0009_donor_name'),
    ]

    operations = [
    ]
