# Generated by Django 2.0.5 on 2018-05-27 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0012_merge_20180525_0954'),
        ('scraping', '0011_donor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='posting.Group'),
        ),
    ]
