# Generated by Django 2.0.5 on 2018-06-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0016_group_is_horoscopes'),
        ('scraping', '0015_record_failed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_sign', models.CharField(max_length=128, null=True)),
                ('text', models.TextField(max_length=2048, null=True)),
                ('post_in_group_date', models.DateTimeField(null=True)),
                ('image_url', models.CharField(max_length=256, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horoscopes', to='posting.Group')),
            ],
        ),
    ]
