# Generated by Django 2.0.5 on 2018-08-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0020_auto_20180807_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='add_to_db_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
