# Generated by Django 2.0.5 on 2018-09-02 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0021_horoscope_add_to_db_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='scraping.Donor', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='record',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='posting.Group', verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='record',
            name='post_in_group_date',
            field=models.DateTimeField(null=True, verbose_name='Дата постинга в сообществе'),
        ),
    ]
