# Generated by Django 2.0.5 on 2019-03-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0033_merge_20190223_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Донор забанен'),
        ),
    ]
