# Generated by Django 2.0.5 on 2019-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0033_merge_20190223_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('gif', 'gif'), ('picture', 'picture')], max_length=16)),
            ],
        ),
    ]
