# Generated by Django 2.0.5 on 2019-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0036_auto_20190331_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='average_views_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Среднее количество просмотров поста'),
        ),
    ]
