# Generated by Django 2.0.5 on 2019-04-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0036_auto_20190331_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_involved_now',
        ),
    ]
