# Generated by Django 2.0.5 on 2019-04-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0037_auto_20190408_1139'),
        ('scraping', '0037_remove_record_is_involved_now'),
    ]

    operations = [
    ]
