# Generated by Django 2.0.5 on 2020-04-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0044_record_candidate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='candidate_number',
            field=models.IntegerField(editable=False, null=True, verbose_name='Идекс по рейтингу'),
        ),
    ]
