# Generated by Django 2.0.5 on 2020-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0046_horoscope_copyright_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='index_number',
            field=models.IntegerField(null=True),
        ),
    ]
