# Generated by Django 2.0.5 on 2020-09-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0048_auto_20200822_1302'),
        ('scraping', '0047_record_change_status_time'),
    ]

    operations = [
    ]
