# Generated by Django 2.0.5 on 2020-09-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0050_horoscope_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horoscope',
            options={'ordering': ['index']},
        ),
    ]
