# Generated by Django 3.2.23 on 2024-05-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0054_auto_20211209_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='rates',
            field=models.PositiveSmallIntegerField(default=0, help_text='От 5555 до 9999, случайные значения'),
        ),
    ]
